version: 1.0.0
app:
  dev: true
  listen: localhost # production set: 0.0.0.0
  prefix: /api/v1
  port: 8888
  cpu: 2 # if fiber.Config.Prefork=True
  logs:
    log: console
    access: storage/logs/access.log
