version: 1.0.0
app:
  dev: true
  listen: localhost # production set: 0.0.0.0
  prefix: /api/v1
  port: 8888
  cpu: 1 # if cpu < 2: fiber.Config.Prefork=false
  logs:
    log: console
    access: storage/logs/access.log
auth:
  admin:
    password: as;djfeosava
